version: "3"

services:
  pygeoapi:
    build: 
      context: .
    environment:
      - PYGEOAPI_URL=http://localhost:5000

    volumes:
      - ./sta.config.yml:/pygeoapi/local.config.yml
    ports:
      - 5000:80
